### ISSUE TITLE
Devemos usar o Flat-Free?

### ISSUE THREAD

**Issue by marcelomatz** [desenvolvedoresweb/livros#1]
O @verzola deu a seguinte sugestão:

Falando um pouco do site da comunidade também, o que acham de usarmos uma interface Flat para ele? Para ficar bem simples e minimalista.
http://designmodo.com/flat-free/

O que vocês acham?

**Comment by natanaelphp** [comment]
eu sou totalmente a favor!

**Comment by Agneli** [comment]
Acho que as discussões deveriam ser feitas pela comunidade, ja que la todos podem opinar. 
Ai usaríamos o github só para a execução do projeto mesmo.

**Comment by bernardodiasc** [comment]
como não participei do hangout, to meio por fora dos objetivos do projeto. essas Issues serão bastante úteis pra delegar responsabilidades (ex: documentação inicial, design da página, revisão do conteúdo etc).

@Agneli tem razão nesse ponto. essa questão pode ser discutida na comunidade, mas por aqui iremos discutir a execução dela. no caso desde definir um responsável (ou mais) como acompanhar o desenvolvimento da tarefa...

**Comment by marcelomatz** [comment]
Eu acredito que podemos utilizar as Issues para discutir tudo o que for relevante para o projeto, e deixar a comunidade para discutir assuntos do dia-a-dia, como já é feito hoje.

Vamos aguardar a opinião dos demais membros e ver se há um consenso entre todos. A partir daí vamos começar a pautar os assuntos relativos ao projeto.

**Comment by verzola** [comment]
Opa, primeira vez utiliando esse "Issues", e gostei muito.
Acho interessante usarmos o Issues para todos assuntos que envolverem o projeto, e deixamos os "assuntos do dia-a-dia", como o @matzemb disse, para a comunidade. Pois se não encheríamos a comunidade de posts sobre decisões do projeto, e o pessoal ficaria meio perdido por lá.

**Comment by highlabs** [comment]
Concordo com o @matzemb sobre as questões relevantes. xD Mas a comunidade serve pra sugestões, etc. Senão vira bagunça. (eu acho! :)

Sobre a questão do flat, apoio 100%.
Na comunidade já sugeri o [FlatStrap](http://www.littlesparkvt.com/flatstrap/index.html).

Se for ter uma página de desenvolvimento web, tem que ser no minimo 100%. hahaha E como é tendencia, não vejo porque não.

Aqui tem o link de um Pintrest sobre flat:
http://pinterest.com/warmarc/flat-ui-design/

E mais 2 artigo, um enorme e outro mas resumido.
http://sachagreif.com/flat-pixels/
http://readwrite.com/2013/02/15/forget-skeuomorphism-the-digital-world-is-flat

**Comment by leandroruel** [comment]
eu nao sei com o que vocês estão mais preocupados, se é com o livro ou se é com o "site" do livro, acho que era melhor todo mundo se concentrar antes em definir logo o conteúdo do livro, e começar a fazê-lo, que vai exigir apenas o Word e só depois a gente pensar no marketing do livro, que é site e etc...é minha opinião

**Comment by highlabs** [comment]
Não vejo porque uma coisa iria interferir com a outra. :) As vezes a uma galera não tem talento pra escrever artigos e ajuda criando o site. Vantagens vindas do opensource... hahaha

**Comment by leandroruel** [comment]
sim, mas ate agora estamos no meio termo. e nao saimos disso =/

**Comment by tarciozemel** [comment]
http://designhash.com/examples-flat-design-web-design/

**Comment by highlabs** [comment]
@leandroruel então, basta criar outra issue sobre o conteúdo! :)

Outra sugestão é um layout One page:
http://onepagelove.com/

**Comment by tarciozemel** [comment]
One Page acho legal, também, sendo que One Page e Flat Design não são mutuamente excludentes!  :sake:

**Comment by felipdcz** [comment]
Da hora é usar o propósito do livro/site/comunidade pra explorar novas ferramentas em conjunto, trocar figurinhas e aprender. Ao mesmo passo que o projeto se solidifica e se torna real, muitos vão saindo das trevas e descobrindo seus talentos ideais dentro e fora da comunidade.

Quero dizer, é legal focar no objetivo e faze-lo caminhar, mas eu por exemplo, este post é minha primeira interação no Github desde o meu cadastro.. Descobrindo.... e a mente voa longe nos primeiros momentos, depois volta.

**Comment by bernardodiasc** [comment]
@dkndzn massa cara. a ideia é essa tambem, usar e aprender. qualquer dúvida que tiver sobre GIT e Github pode chamar.
