### ISSUE TITLE
Organização do repo

### ISSUE THREAD

**Issue by tarciozemel** [desenvolvedoresweb/livros#2]
Temos que pensar numa melhor organização do repo, já que este livro será o primeiro de muitos projetos interessantes na comunidade. o/

Para começar, minha sugestão é que renomeemos de "e-book" para "livros" e, lá dentro, ter uma pastinha para cada um deles.

**Comment by leandroruel** [comment]
de acordo

**Comment by bernardodiasc** [comment]
o @matzemb é o responsável pela conta no github. libera pros membros criar repos.

**Comment by leandroruel** [comment]
vamos definir o título do livro? o que acham? questões:
- haverá um autor para cada assunto?
- vamos definir os responsáveis pelo site?
- escolher o design do site?
- vamos discutir as melhorias anteriormente já sugeridas?
- vamos criar uma lista de tarefas e distribuir entre os membros?

**Comment by marcelomatz** [comment]
Quem sabe um título modesto, como: A bíblia do Desenvolvimento Web rsrs

Sim, já que vamos unir tantas forças, vamos ter tantos profissionais colaborando, podemos garantir que informações teremos muitas :)

**Comment by felipdcz** [comment]
Título é a última coisa.

Acho que o importante seria descrever com poucas palavras (lista talves) o que será abordado, e à partir daí começar a produzir o conteúdo de forma colaborativa, lapidando os tópicos e capitulos, depois organizar a ordem de tudo, preparar as ilustrações, revisar.
No meio tempo acredito que o nome aparecerá, mas nao é importante, ele cria uma falsa expectativa.
Tambem o design, os designers inspirados pelo conteudo sendo produzido poderão trabalhar em conjunto.

Sem o conteúdo acho que conseguiremos uma belíssima embalagem vazia, hehe... a bíblia do brasileiro na web, seria um belo título... OH NOESSS... estou brincando, acho que podemos mudar esse karma brasileiro.

Eu sei que opiniões (como as minhas) teremos muitas, mas colaboração ativa, vamos ver, espero que sim... eu sou noob e to reaprendendo tudo de novo... não consigo imaginar onde poderia contribuir se não com estas analises.. que eu espero nao serem demagogas.

**Comment by felipdcz** [comment]
Acredito tb na importancia de uma liderança, não no sentido de distribuir funções e/ou dar ordens mas sim tomar iniciatívas no desenvolvimento do projeto, um coordenador, não sei se é este o termo, o que acham?

**Comment by leandroruel** [comment]
relevante...vamos dar início à distribuição de funções, conforme foi discutido antes dentro da comunidade em um tópico do daniel oshiro.
então...vamos começar sabendo com que parte deste projeto o pessoal quer colaborar!
assim reunimos todas as informações e organizamos tudo. :+1:

**Comment by tarciozemel** [comment]
Se fôssemos colocar em votação, meu voto seria para este primeiro livro conter o basicão de desenvolvimento web. Algo como: como surgiu a web; desenvolvimento em camadas; básico de HTML e CSS (talvez JS); etc (de repente, uma intro a controle de versões e Git/GitHub para o pessoal já começar a ficar esperto para contribuir mais por aqui, também).

Com esta abordagem, além de disponibilizar um bom material para quem, realmente, está começando, acredito que conseguiríamos começar a formar bases fortes para materiais vindouros (e já começar a espalhar o nome da Comunidade pela web à fora).

Também penso que, nesse momento, fechar o título do livro não seja tão importante, assim; entretanto, algo como "Começando a desenvolver a web" traduz a _essência_ do conteúdo, de uma certa maneira.

O que acham da sugestão? Se for do agrado, já podemos pensar em fechar um sumário e definir as pessoas que vão escrever os capítulos (seja de forma individual, em dupla ou totalmente colaborativa).

PS: Dá pra explicar melhor esse negócio das "funções"?

**Comment by bernardodiasc** [comment]
Legal @tarciozemel 

Já da pra montarmos um sumário no wiki e ir criando as páginas. Vou poder contribuir com material talvez na segunda quinzena do mes que vem.

## Sugestão de Temas
- História (internet, browsers, table e tabless, ...)
- Linguagens (server-side, client-side, preprocessors, templating, transport, ...)
- Ferramentas (frameworks, libraries, cms, ide, ...)
- Metodologias (mvc, dry, tdd, ...)
- Perspectiva (acessibilidade, mobile, ...)

Deixo aberto pra mais sugestões.

**Comment by leandroruel** [comment]
gostei das sugestões também. tem que começar do básico mesmo pra todo mundo entender, e ir aos poucos explicando outros tópicos mais avançados

@tarciozemel modo de falar hehe

**Comment by tarciozemel** [comment]
@germchaos De repente, ao invés de colocar no Wiki, a gente poderia criar uma issue, mesmo, que tem um caráter mais temporário. Gostei das primeiras sugestões, mas acho que temos que ter cuidado para não colocar coisas muito avançadas. Na lista que você colocou, por exemplo, imagina alguém que _nunca viu_ desenvolvimento web se deparando com as coisas em "Ferramentas" e "Metodologias"... rsrs

@leandroruel ;-)

**Comment by bernardodiasc** [comment]
Acho que da pra falar de tudo num contexto geral. É importante pra alguem que ta começando saber que existem tais coisas. Mesmo que não compreendam os detalhes, vale a pena passar uma visão do todo e depois, num outro livro talvez, ir a fundo em cada tema.

Quando começei, todo material que encotrava falava da história da web, como surgiu o PHP etc. Depois iam complicando um pouco (pra quem ta começando) e eventualmente comentavam ferramentas ou métodos sem explicar direito o cenário. Digo, as vezes o nivel de complicação subia de um capítulo pro outro consideravelmente.

Digamos, se fosse explicar pra alguem que ta começando sobre Metodologias e Ferramentas, provavelmente eu não iria dar exemplos de execução. Não convém, só confunde. Mas diria que MVC é quando se separa o produto/sofware em 3 camadas, sendo que cada uma representa uma coisa e as coisas são assim por isso isso e aquilo. Mas não abriria um código de Zend e jogaria na cabeça do coitado um exemplo de ToDo... rs

Até mesmo no que se refere a história da web, tem tanto assunto que daria pra fazer um livro só disso... são décadas de evolução numa área que evolui muito rapidamente. E com certeza essa rápida evolução ta relacionada com Open Source, que é um assunto importante que esqueci de colocar na lista. =]

Bom, @tarciozemel na prática vc sugere fazer como? Criar uma Issue pra cada tema? ou uma Issue pra percorrer o sumário do livro? Dá pra montarmos milestones tambem com checkboxes... fica organizado e cada membro pode escolher um assunto pra escrever. digo, alguem tem que começar e revisar, mesmo que vários outros contribuam no mesmo tema.

**Comment by tarciozemel** [comment]
@germchaos Concordo! Nesse primeiro momento, tava pensando em criar uma _issue_ só para definirmos o sumário do livro, mas o negócio dos _milestones_ que você falou pode ser uma boa, mesmo, que aí todo mundo vai sabendo o progresso da coisa.

Não sei organizar isso direito aqui no GitHub. Cada _milestone_ tem várias tarefas, é isso? Se for, acho que, depois de definir o sumário e quem vai escrever cada coisa, podemos fazer um _milestone_ pra cada capítulo (e para tarefas relacionadas, tipo "criação de capa", "site", etc).

O que me dizem?

**Comment by marcelomatz** [comment]
Eu concordo com vocês sobre começar fazendo o sumário do livro, e logo após podemos começar a definir quem vai escrever o que. Sobre os milestones eu não sei como funcionam :(

Vamos amadurecendo essa ideia e colocando em prática. O legal é que essas issues já fazem parte do projeto, e são partes integrantes do livro, ou pelo menos do projeto :)

**Comment by leandroruel** [comment]
não podemos esquecer que temos que escrever um conteúdo para a nossa atual época, pois esse livro poderá servir daqui a 1, 2 ou mais anos...então, acho que é uma boa que tenha por exemplo alguma coisa explicando sobre a importância do mobile, o que não podemos é escrever um livro que durará apenas 1 ano e logo estará ultrapassado.

=)

**Comment by bernardodiasc** [comment]
@leandroruel isso ai. quando escrevi o tema "perspectiva" havia escrito "futuro" antes, mas entenda como Perspectiva a visão que temos agora do que vem pela frente, isso inclui as tendencias de hoje e as de amanhã. Mobile certamente é um dos temas mais importantes na seção de Perspectiva, já que em alguns anos tablets serão mais presentes na vida das pessoas que notebook.

@tarciozemel @matzemb milestones como o proprio nome já diz, representa um marco no projeto. podemos demarcar um projeto usando parametros temporais ou funcionalidade ou versões. sendo que dentro de cada milestones são definidos uma série de objetivos, e todos eles precisam ser concluidos para alcançar um milestone.

No caso deste projeto em particular, ter o Sumário e os Redatores responsáveis definidos é com certeza um milestone. depois teriamos marcos como Redação (provavelmente o mais longo de todos), Site (inclui artes graficas e inserção do conteúdo), Livro (arte da capa, diagramação, editoramento, etc)... e por aí vai. pode-se desmembrar mais e dividir mais ainda os marcos, por exemplo ao invés de Redação, haver marcos em cada tema.

O legal é que usando o Github, podemos criar branches independentes, então alguns milestones podem fluir paralelamente sem afetar os outros. Podemos então em determinado momento fazer um merge no branch master e ter todo o material concluido lá. Nunca vi livro sendo escrito assim, mas tamo aqui pra isso pra aprender e pra inovar hehehe ou então usar o wiki.

Nessa primeira etapa vamos precisar de mão de obra, se conhecerem mais gente que possa ter interesse em participar, convidem-nas. E não podemos esquecer de levar algumas discussões pro G+ vez ou outra.

@tarciozemel assim que o assunto principal desta Issue estiver resolvido, tenha a honra de fechá-lo. nesse Issue o assunto pulou de um assunto pra outros e ainda não enxerguei exatamente a conclusão da "Organização do repo".

**Comment by tarciozemel** [comment]
@germchaos Abri o tópico, justamente, para pensarmos nisso de uma vez para já valer para todos. Nos livros, por exemplo, acho que fica bem organizado um repo "livros" com várias pastas dentro, uma para cada livro (e, o resultado final, vamos disponibilizando em formato virtual no site, num formato já "fechado").

Aproveitando que você já tem uma visão melhor de como as coisas podem ser organizadas aqui no GitHub, o que sugeriria para nosso caso, em específico? Acha que desse jeito funcionaria? Levando em consideração que teremos vários livros e, muito provavelmente, também projetos de codificação, mesmo, como poderiam ser organizados, efetivamente, esses _milestones_?

**Comment by leandroruel** [comment]
Se aceitam uma sugestão também, o site de cada livro pode conter "Exercícios" para reforçar os aprendizados, ou até mesmo _screencasts_! (WOW quem não vai aprender algo com tudo isso?) =p

**Comment by bernardodiasc** [comment]
perfeito @tarciozemel, comentei sobre o foco no objetivo das issues de maneira geral, eu mesmo perdi o foco varias vezes nessa issue.

sobre a organização, ainda estou tentando ver o projeto todo na minha cabeça. os ultimos 2 hangouts não consegui comparecer, to meio que perdido só imaginando qual o teor do projeto todo, que talvez já tenha sido discutido nos hangouts.

Então vou partir do seguinte, vamos criar milestones pra cada sub-projeto (livros da coleção). Ou seja, (inicialmente) vamos criar o milestone do primeiro livro. Obviamente essas milestones não terão data de entrega já que esse é um projeto colaborativo e depende muito do tempo livre de cada um.

Então o proximo passo importante é sabermos o que vai ter nesse livro?

Vou dar a minha sugestão e gostaria que todos sugerissem tambem.

O primeiro livro pode ser uma visão geral do todo, abordando o máximo de assuntos possível só que de uma forma "for dummies", mais superficial. Os outros livros podem ser mais específicos de cada tema e aprofundados. O que acham? O sumário sugerido está no comentário https://github.com/desenvolvedoresweb/livros/issues/2#issuecomment-16215474 .

**Comment by marcelomatz** [comment]
Opa! Muito bom ver todo mundo unido por um bem maior. 

Seguinte, o que o @germchaos falou condiz com a minha ideia inicial. "Abordar o máximo de assuntos, porém de um jeito superficial".

Querem fazer um Hangout esse final de semana, para decidir algo?

**Comment by leandroruel** [comment]
na milestone será incluido também tópico para definir o layout da capa, páginas e etc do livro? :exclamation:

**Comment by bernardodiasc** [comment]
sim @leandroruel , o milestone representa um marco/objetivo. durante todo o tempo serão criadas issues diversas (igual a essa) sobre particularidades, e essas issues podem ser relacionadas com um determinado milestone. também no tópico principal do milestone descreveremos todas tarefas, como por exemplo layout da capa, diagramação, etc.

**Comment by bernardodiasc** [comment]
Na página https://github.com/desenvolvedoresweb/livros/issues vcs vão conseguir filtrar as Issues de cada Milestone. Já dei o primeiro passo nesse sentido. 

Aqui https://github.com/desenvolvedoresweb/livros/issues/milestones voces porão ver todos os milestones. Creio que alguns de vocês possuam permissão total administrativa, isso significa que podem tambem editar as milestones/issues de outras pessoas. Usem isso com sabedoria. Deixo aberto para complementarem a descrição desta primeira milestone, e tambem ir marcando os checkboxes do que for concluido.

A ideia de trabalhar com pastas nos repos é boa, os arquivos vão ser markdown ou html ou outro? Vai ser o site direto ou o site vai ficar mais pra frente?

**Comment by felipdcz** [comment]
Certo, lembrando aos web designers que este tambem faz parte da história da internet.

**Comment by tarciozemel** [comment]
Acho que poderíamos definir em markdown (usando HTML para elementos não suportados, como &lt;del&gt;) e, também, vamos pesquisando uma maneira de "converter" arquivos de um repo num arquivo de livro digital (porque, como o @matzemb falou, se não tiver nada, vamos ter que criar a nossa).
