### ISSUE TITLE
Bases conceituais e filosóficas da comunidade

### ISSUE THREAD

**Issue by tarciozemel** [desenvolvedoresweb/livros#3]
Pessoal, acabei de atualizar o README do repo "livros" para algo mais condizente. Anteriormente, constava ainda a descrição relativa a somente 1 projeto, mas, como já chegamos à conclusão, foi mais interessante uma melhor organização.

Acredito que devamos, também, organizar as bases conceituais e filosóficas da comunidade, deixando claro qual é o propósito, como pensamos em agir, o que admitimos ou não, etc, e deixar isso bem claro para todos que estejam tendo seu primeiro contato.

Essa modificação do README foi mais um _bugfix_, mas está longe de ser algo definitivo. Acredito que o melhor seja, depois dessa definição teórica, elaborarmos um documento completo para colocar no README (ou lincar para algo que esteja no site).

**Comment by marcelomatz** [comment]
@tarciozemel Ficou muito melhor a definição do README :+1: 

Acho que temos que fazer um Hangout para discutir os detalhes do projeto.

**Comment by leandroruel** [comment]
vamos criar um evento dentro da comunidade chamando os envolvidos para definirmos os detalhes do projeto =)
