### ISSUE TITLE
definir convenções

### ISSUE THREAD

**Issue by leandroruel** [desenvolvedoresweb/livros#4]
o que acham de usarmos nas páginas do livro algumas "convenções", como funciona? alguns livros que falam sobre programação usam isso, normalmente tem alguma dica, alerta e etc...e fornecem informações uteis ao leitor sem que o autor do livro necessite mudar o assunto para explicar algo em especifico. simplesmente insere a convenção, veja abaixo como ficaria

![conven es-livro](https://f.cloud.github.com/assets/2836002/331972/9c05c07a-9c0c-11e2-8153-7b1daa16f0a2.png)

**Comment by bernardodiasc** [comment]
isso é bom. torna a leitura mais didática...

**Comment by tarciozemel** [comment]
Eu acho a ideia até válida, mas, geralmente, se tem que explicar no início é porque não está claro o suficiente. =P

**Comment by leandroruel** [comment]
nos livros do maujor tem essas convenções, e também pode-se colocar os códigos com cada linha enumerada e syntax highlight igual nas IDE que baixamos por ai, isso melhora MUITO visualmente a leitura.

Ex:

```
1. <style>
2. div {
3.   width: 350px;
4.   height: 250px;
5.   border: 1px solid #ccc;
6.      }
7. </style>
```

**Comment by bernardodiasc** [comment]
``` css
div {
    width: 350px;
    height: 250px;
    border: 1px solid #ccc;
}
```

:godmode:

**Comment by leandroruel** [comment]
:octocat: era isso mesmo =)

**Comment by marcelomatz** [comment]
+1

**Comment by bernardodiasc** [comment]
uai... não sei pq reabri essa issue.. auhauha  _closed_ :beers:
