### ISSUE TITLE
Definição do Sumário do primeiro livro

### ISSUE THREAD

**Issue by bernardodiasc** [desenvolvedoresweb/livros#5]
Buenas, estou criando esta issue para discutirmos o que será abrangido no primiero livro.

A partir desse sumário iremos produzir o conteúdo, então é legal que começemos por aqui, antes mesmo do próprio título do livro.

Vou iniciar essa issue com sugestões que já havia colocado anteriormente (em #2 ) e adicionadas algumas outras:
## Sugestão de Temas
- **História**
  - Como surgiu a Internet
  - História dos Navegadores
  - HTML antes das folhas de estilo
  - Internet antes do Google!
- **Linguagens**
  - Server-side _(PHP, .NET, Ruby, Python, JAVA, etc...)_
  - Client-side _(HTML, CSS, Javascript, etc...)_
  - Preprocessors _(LESS, SASS, Stylus, etc...)_
  - Templating _(XSLT, Blade, Mustache, etc...)_
  - Transport _(XML, JSON, etc...)_
- **Ferramentas**
  - Frameworks 
  - Libraries
  - CMS
  - IDE
- **Metodologias**
  - MVC - Model View Controller
  - DRY - Don't Repeat Yourself
  - TDD - Test Driven Development
  - SCRUM
- **Perspectiva**
  - Acessibilidade
  - Mobile
  - Open Source!

---

Este não é o sumário do livro em si, é muito mais **sugestão de temas**. Opiniem sobre o que é válido conter no primeiro livro e o que não convém. E tambem escolham os temas que desejam trabalhar.

**Comment by bernardodiasc** [comment]
Não podemos esquecer de **"The Rise and Fall of the Flash!"** assim como HTML5 e CSS3, que além de tantas coisas, veio pra substituir o Flash.

**Comment by tarciozemel** [comment]
Tá ficando muito maneiro! Pessoalmente, acredito que não tenha como explicar "Metodologias" sem a pessoa saber sobre programar, mesmo; como, neste Livro, só vamos dar uma passada em cada, não sei se cairia bem.

Também não entendi bem o item "Libraries" em "Ferramentas", já que existem bibliotecas server-side e cliente-side, além de os 3 principais já estarem sendo abordados, então tiraria, também (bem como "Templating" em "Linguagens").

Quanto ao Flash, eu acho que a gente poderia, simplesmente, ignorar (talvez falar alguma coisinha na "História").

Pegando a partir da sua proposta, @germchaos, eu colocaria (marcações com ":question:" são dúvidas se o respectivo tópico/item deve entrar; ":warning:" são itens a serem complementados/discutidos):
- História
  - Como surgiu a Internet
  - História dos navegadores 
  - HTML antes das folhas de estilo
  - Web antes do Google!
- Linguagens
  - Diferenciação entre Server-side e Client-side
  - Server-side
    - PHP
      - História
      - Vantagens/pontos fortes e desvantagens/pontos fracos
      - Frameworks
        - CakePHP
        - CodeIgniter
        - Laravel
        - Symfony
        - Yii
        - Zend
        - Tabela comparativa
      - CMSs
        - WordPress
        - :warning: Colocar mais
        - Tabela comparativa
    - Ruby
      - História
      - Vantagens/pontos fortes e desvantagens/pontos fracos
      - Frameworks
        - :warning: Principais frameworks
        - Tabela comparativa
      - CMSs
        - :warning: Principais CMSs
        - Tabela comparativa
    - Python
      - História
      - Vantagens/pontos fortes e desvantagens/pontos fracos
      - Frameworks
        - :warning: Principais frameworks
        - Tabela comparativa
      - CMSs
        - :warning: Principais CMSs
        - Tabela comparativa
    - JAVA
      - História
      - Vantagens/pontos fortes e desvantagens/pontos fracos
      - Frameworks
        - :warning: Principais frameworks
        - Tabela comparativa
      - CMSs
        - :warning: Principais CMSs
        - Tabela comparativa
    - .NET
      - História
      - Vantagens/pontos fortes e desvantagens/pontos fracos
      - Frameworks
        - :warning: Principais frameworks
        - Tabela comparativa
      - CMSs
        - :warning: Principais CMSs
        - Tabela comparativa
    - Estatísticas de uso de cada linguagem no mundo
    - Editores/IDEs
      - Aptana
      - Eclipse
      - Netbeans
      - Notepad++
      - Sublime Text
      - :warning: Colocar mais :question:
  - Client-side
    - Desenvolvimento em camadas
      - Camada de conteúdo / HTML
      - Camada de apresentação / CSS
      - Camada de comportamento / JS
    - Pré-processadores
      - LESS
      - SASS
      - Stylus:question:
      - Frameworks
        - Foundation
        - InK
        - Twitter Bootstrap
        -  :warning: Colocar mais
      - Bibliotecas
        - jQuery
        - YUI Library
        - QuoJS
        - Zepto
        -  :warning: Colocar mais
  - Transporte
    - Importância de "linguagens de transporte"
    - JSON
    - XML
- Controle de versões
  - História:question:
  - Principais vantagens
  - Tipos
  - Mais usados:question: 
    - Bazaar
    - CVS
    - Git
    - Mercurial
    - SVN
  - Git
    - História :question:
    - Principais vantagens
    - Comandos básicos
    - GitHub
      - História :question:
      - Como criar uma conta
      - Como criar um repo
      - Como forkar um repo
      - Pull Request
      - Como contribuir nos projetos da Comunidade
- Perspectivas
  - Acessibilidade
  - Mobile
  - Free Software / Open Source
    - Como surgiu Free Software
    - Como surgiu Open Source
    - Vantagens em se usar Free Software / Open Source
- Indicações
  - Sites brasileiros
  - Sites não-brasileiros
  - Livros brasileiros
  - Livros não-brasileiros

Me desculpem não conseguir pensar em mais nada no momento, mas 2h da matina com absinto na cabeça, foi "o melhor que tá tendo"! :sake:

Se acharem que ficou legal, vamos continuar a partir daí.

**Comment by leandroruel** [comment]
_(imaginando essa bíblia debaixo do meu braço...)_
em _"indicações"_, no post do @tarciozemel eu incluiria também perfis de redes sociais a se seguir.
_Ex:_ @smashingmag, @Designmodo e etc...além de perfis do Google+, que á para fortalecer a presença do pessoal nas comunidades.
- Indicações
  - Sites brasileiros
  - Sites não-brasileiros
  - Redes sociais :question: 
  - Livros brasileiros
  - Livros não-brasileiros

**Comment by Agneli** [comment]
Pessoal desculpem a discordância, mas acho que deveria ser definido um único tema para o livro.
Achei legal as sugestões, mas acho que deveríamos escolher um tema e aprofundar um pouco mais nele.
Pois ai tem de "Como surgiu a internet" á Github.
Mesmo se fosse abordar o mais superficial de cada assunto o livro ainda ficaria enorme e meio que "falando sobre tudo sem falar sobre nada".
Não sei, talvez seja só ignorância minha, mas acho que aí tem assunto pra dezenas de livros.

Uma sugestão, que eu acho que seria interessante é criar um "Guia de desenvolvimento web para iniciantes",
onde poderíamos abordar alguns assuntos antes citados, porém mais centralizado em desenvolvimento, sem falar de metodologias, controle de versões, história e tal.

Bom, é só uma opinião, caso não curtam é só ignorar ^^
Estou curtindo o envolvimento e a dedicação de vocês pra desenvolver este projeto.

Valeu
Agneli

**Comment by tarciozemel** [comment]
@Agneli Se você pensar bem, "Guia de desenvolvimento web para iniciantes" poderia ser até o título para um livro com esse sumário... rsrs

A gente tinha comentado que o primeiro seria um geralzão, mesmo, justamente para dar essa ["introdução"](http://emocoesdeumwebdev.tumblr.com/post/47763489816/introducao-ao-desenvolvimento-web) para os novatos e, posteriormente, aprofundar nos N temas de desenvolvimento web.

Pessoalmente, acredito ser uma estratégia legal, já que, a partir deste primeiro "genérico", a gente pode ir desmembrando os assuntos dentro de uma sequência lógica (dando até pra fazer citações de livros anteriores). 

**Pessoal de outras linguagens que não PHP: complementem as lacunas aê! ;-)**

**Comment by leandroruel** [comment]
Então quer dizer que, o primeiro livro poderá ser considerado o Volume I, e os próximos poderão vir como Volume II, III e etc... ?

**Comment by tarciozemel** [comment]
@leandroruel Aí já não sei; não sei como funciona, exatamente, essa divisão por "volumes" em livros. Mas a Comunidade querendo e sendo melhor para o projeto, com certeza! =)

**Comment by leandroruel** [comment]
percebi que neste primeiro livro não será abordado banco de dados, isso poderia ser então um assunto para um próximo livro? o que acham? :question:

**Comment by tarciozemel** [comment]
@leandroruel Poxa, verdade. Se o pessoal julgar que caberia para um livro introdutório, poderia entrar nesse, mesmo, na minha opinião!

**Comment by marcelomatz** [comment]
Sensacional @tarciozemel @leandroruel @germchaos @Agneli :)

A cada dia o projeto ganha mais estrutura. Realmente se seguirmos neste caminho, teremos desenvolvido a bíblia do desenvolvedor web.

**Comment by leandroruel** [comment]
do jeito que esta sendo planejado aqui, na minha humilde opinião, será a primeira biblia do DpW do Brasil

**Comment by tarciozemel** [comment]
Moçada, vamos ver se divulgamos mais para o pessoal das outras linguagens virem e complementar a proposta do sumário!

**Comment by marcelomatz** [comment]
Pessoal quem sabe um hangout neste domingo para falar algumas coisas relativas ao livro?

**Comment by kelsam** [comment]
Então, galera. Gostei da ideia dos volumes.
Na minha opinião, se colocarmos todo o conteúdo dentro de um E-book só, ficaria muuuuuito grande, ficando cansativo de ler. Caso fizéssemos a separação do conteúdo dentro de volumes, além de o primeiro desses volumes sair mais rápido, nos deixando com tempo pra fazer os outros, vai ficar melhor de ler. E também tem aquela "ansiedade" do leitor em saber o que vai ter no volume II, III IV e etc... Acho que seria uma boa fazermos tipo assim:

<strong>História – Volume I (Intro)</strong>
        Como surgiu a Internet
        História dos Navegadores
        HTML antes das folhas de estilo
        Internet antes do Google!

<strong>Linguagens – Volume II</strong>
        Server-side (PHP, .NET, Ruby, Python, JAVA, etc...)
        Client-side (HTML, CSS, Javascript, etc...)
        Preprocessors (LESS, SASS, Stylus, etc...)
        Templating (XSLT, Blade, Mustache, etc...)
        Transport (XML, JSON, etc...)

<strong>Ferramentas – Volume III</strong>
        Frameworks
        Libraries
        CMS
        IDE

<strong>Metodologias – Volume IV</strong>
        MVC - Model View Controller
        DRY - Don't Repeat Yourself
        TDD - Test Driven Development
        SCRUM

<strong>Perspectiva – Volume V</strong>
        Acessibilidade
        Mobile
        Open Source!

<b>Todos, é claro, com os subníveis que o Tárcio propôs.<b/>

Achei mais interessante ainda quando vi que deu um total exato de 5 volumes, ficaria uma boa coletânea. E todos os volumes podiam ter a mesma capa, porém com cores diferentes. Isso das cores também sugere que mudemos a capa, pois se vai ser com várias cores, não poderemos usar a logo do G+, mesmo porque, apesar de ter sido criado pela comunidade do G+, o foco não é a comunidade, mas sim o conteúdo (Internet, Linguagens, Códigos, etc...) – Creio que poderíamos fazer uma capa mais condizente com o conteúdo, porém sem deixar o leitor cego com uma festa de carnaval... teria apenas uma cor, com alguns elementos pretos, cinzas e brancos.

O que acham?

– Samuel aqui.

**Comment by tarciozemel** [comment]
:+1: pra ideia dos volumes do @leandroruel e @kelsam, então! Explicadinho assim, vocês me convenceram! x)

**Comment by kelsam** [comment]
Opa!! Aí sim! KKK \õ/
Muito bom.
E como vai ser, quanto à capa...? Já está definido ou ainda estão olhando?

**Comment by tarciozemel** [comment]
@kelsam Ainda sendo definido. Dá uma olhada na issue https://github.com/desenvolvedoresweb/livros/issues/6.

**Comment by Agneli** [comment]
Concordo com a proposta de dividir em volumes, vai ficar menor, porém, ainda assim creio que abordará muito superficialmente cada assunto, como no volume II por exemplo, temos mais de 15 linguagens e tecnologias que foram citadas, isso sem contar as inúmeras outras que não foram citadas, então acho que será algo bem superficial, ou o livro ficará enorme.
Mas de qualquer forma, melhor assim, dividido em volumes.

**Comment by tarciozemel** [comment]
@Agneli É, pelo que estou entendendo, essa primeira "coleção" (rsrs) vai ser só para apresentar o mundo webdev, mesmo, para quem não conhece nada ficar sabendo das tecnologias e possibilidades.

Aí, depois, a gente até faz livros sobre cada linguagem e sobre itens específicos de cada linguagem! o/

**Comment by Agneli** [comment]
Show de bola @tarciozemel.
Go go Power Rangers então kkkkkkk

**Comment by bernardodiasc** [comment]
minha dúvida ainda é sobre quem vai escrever o que... rs

**Comment by leandroruel** [comment]
bem, podemos fazer assim, vamos escolher as pessoas que irão escrever o conteúdo do livro, e sortear entre eles o assunto, então, aos demais que preferem trabalhar com outras partes do projeto, Ex: capa, layout e divulgação do livro [construção do website] faz-se outro sorteio ou fazemos um hangout para definir quem tem tempo para se dedicar a alguma parte do desenvolvimento do site e etc...

**Comment by kelsam** [comment]
Eu acho a história do sorteio um pouco errada, pois algumas pessoas sabem mais do que outras sobre um assunto. Acho que devíamos discutir sobre quem quer escrever sobre o que e, por exemplo, se duas ou mais pessoas querem escrever sobre CSS, elas se juntam e cada uma escreve um tópico, ou fazem um sorteio entre si pra ver quem vai ser o escritor principal do assuntos, e os outros vão ajudar, revisando os textos e dando idéias. Que tal?

**Comment by bernardodiasc** [comment]
ótima ideia @kelsam, os líderes de cada tópico serão naturalmente os que escolherem o tópico. a função do lider não é saber mais que os outros, é desenvolver o conhecimento junto com os outros.

minha sugestão pra quem já tiver assunto na manga: abra uma "issue" no github com o assunto, dessa forma ja começa a direcionar uma discussão.

quem se habilita a fazer um site pro projeto? algo do tipo https://docs.djangoproject.com/en/1.5/ ai poderemos usar o site pra publicar os primeiros conteúdos revisados. hospedar o site em sua conta no github e postar na comunidade.

**Comment by tarciozemel** [comment]
Concordo com o @kelsam, esse negócio de sorteio não vai dar muito certo. Não porque eu nunca me dou bem em sorteios, mas pelos motivos que ele falou, mesmo.

@germchaos Ah, podemos até começar a ver o site, mas não seria legal publicar só quando o primeiro volume já estivesse finalizado? Aí o povo faria o download e tudo o mais.

Se estiverem de acordo, vamos abrir uma issue específica sobre o Volume I, então?

**Comment by kelsam** [comment]
@tarciozemel Por mim, já podemos começar sim. Aliás, já está passando da hora. KKK

**Comment by leandroruel** [comment]
retomando esta discussão, que tal darmos inicio?

**Comment by bernardodiasc** [comment]
galera, eu to sem previsão de tempo livre... enquanto os protestos não resolverem a crise inflacionária e os absurdos tributários no país acho que as coisas vão continuar no aperto...

**Comment by bernardodiasc** [comment]
Acho uma boa contribuirmos pro https://github.com/tableless/iniciantes do @locawebstyle
pela dica do @Agneli https://plus.google.com/u/0/109998964993874312955/posts/7ZWNQYEafJZ
e pra dar uma força na decisão, to fechando essa questão (issue)!

**Comment by tarciozemel** [comment]
Segundo estou entendendo até agora, esse projeto é bem melhor e mais "ambicioso" que esse "Guia para Iniciantes". Fechar um tópico desses porque foi lançado (somente) um repo com uma proposta diferente?! #nonsense

**Comment by bernardodiasc** [comment]
Deixo a decisão pra vocês. Mas quantos ninjas temos na equipe pra poder escrever um livro tão grande?

**Comment by tarciozemel** [comment]
@germchaos pelo que entendi não é preciso de ninja algum, só de contribuidores dispostos a ajudar, nem que seja um pouquinho, mesmo que somente no tempo que chamamos de "livre".

Como se tratam se projetos diferentes, nada impede de participar de ambos; só não posso negar minha enorme surpresa quanto à repentina sugestão do abandono do tópico (e do projeto, em si) em prol de um "repo de grife"...

**Comment by bernardodiasc** [comment]
Penso que o que importa mesmo é o que está sendo feito. @tarciozemel, seu proprio blog poderia ser uma das referencias fortes para o livro, basta voce convidar os desenvolvedores a contribuir. Foi o que foi feito no projeto do blog Tabless, que também é um blog muito representativo que contribui muito para o aprendizado de muitos iniciantes e até mesmo experientes.

Se vocês voltarem lá no inicio, entenderão que a proposta dessa Issue é sugerir tópicos de conteúdo para serem desenvolvidos. Várias sugestões foram dadas nos comentários, já podem começar a escrever. Quem já escreve já pode enviar o material, minha sugestão é usar a seção Wiki do Github. Ou um site (html no Github), ou um blog, ou um diretório compartilhado no Google Drive ou Dropbox ou similar, etc...

Já temos 3 capas e nenhum verso.

**Comment by leandroruel** [comment]
@tarciozemel o @germchaos deu uma boa sugestão.

@barramatz qual a sua opinião? vc sumiu do github hehe, também, precisamos de mais gente possível colaborando, tem mais amigos/contatos para chamar para colaborar?

**Comment by mayroncachina** [comment]
Olá pessoal, estava só acompanhando a discussão mais agora resolvi me pronunciar...

Acho que o @germchaos  está certo, estamos com bastante conteudo, vamos agora articular para compilar-los no livro.

Me comprometo a Ajudar com o que for preciso e estiver em meu conhecimento..

Algumas coisas que eu acho que poderiam entrar no sumario...

Algumas bibliotecas como Jquery Mobile e afins, para desenvolvimento móvel utilizando HTML, está no auge agora, acho que seria interessante...

Outra coisa que eu não vi foi nada sobre Node.JS, não seria interessante tb?

**Comment by marcelomatz** [comment]
Já começo pedindo desculpas, pois como disse o @leandroruel eu sumi do GitHub. "Desculpas!"

Eu tenho acompanhado pelas notificações do meu e-mail o que está acontecendo aqui no projeto. E cara, é uma coisa bem simples. Na proporção que pretendemos que o projeto tome, abrangendo todas as áreas de desenvolvimento web e este é o projeto inicial, temos que ter liderança. Liderança de projeto. Sem aplicar alguma metodologia de trabalho, sem aplicar alguns padrões conhecidos de mercado, este vai ser apenas mais um projeto sem continuidade no GitHub.

Que broxante é quando tu encontra um projeto com uma descrição super interessante, mas o conteúdo não é completo? Tu não te motiva a continuar ele, a colaborar com o crescimento daquele projeto.

A solução que eu acredito estar faltando aqui, é definir quem vai gerenciar cada projeto, e qual a forma que vamos ter de acompanhar a evolução desse conteúdo e como os demais vão poder colaborar.

Já que cada um vai colaborar com a livre e espontânea vontade, aplicando o seu conhecimento, é natural que esta pessoa também gerencie o seu tempo. Ou seja, cada um sabe a hora que vai se dedicar a produção de conteúdo.

O repositório não tem outro local para ser, se não aqui mesmo, no GitHub.

Temos que modularizar a produção desse conteúdo de certa forma, que cada área tenha o seu project manager. Até pq ninguém precisa dar um Fork do conteúdo completo, já que para algumas pessoas pode ser mais interessante buscar apenas o conteúdo de JavaScript.

Bueno, alguém quer tomar essa liderança de projeto para si, e delegar/controlar a produção de conteúdo de cada um dos integrantes do time?

Abraço a todos. E não briguem hehehe

**Comment by tarciozemel** [comment]
@germchaos @leandroruel Pois é, já tava pensando em divulgar no blog, sim (embora pense que [a comunidade no G+](https://plus.google.com/u/0/communities/115427116626746420645) tenha muito mais alcance e expressão, mas não deixaria de ser uma ajuda), mas estou esperando uma melhor delineação dos conteúdos iniciais para fazer um convite mais focado (dado que, como estamos falando, vamos produzindo as "edições" aos poucos).

@barramatz Cara, é uma sugestão legal, embora eu não tenha certeza se colocar somente 1 pessoa como "líder" ficaria interessante para todos que contribuirão. De repente podemos pegar algumas pessoas somente para organizar/indicar as coisas e, quando do surgimento de pontos conflitantes, submeter as questões ao "voto popular": uma enquete ou algo assim. E fica tranquilo que discutir é diferente de brigar! hehe

Então, dando prosseguimento à ideia que o @kelsam propôs e a maioria dos que estão acompanhando o tópico se manifestou a favor, vamos passar a uma discussão concreta dos conteúdos: o que me dizem de criarmos um milestone para o **Volume 1** (em arábico, mesmo) e criarmos issues específicas para este objetivo inicial?

**Comment by marcelomatz** [comment]
@tarciozemel A minha ideia não ficou muito clara. O objetivo era ter gerentes para cada assunto, por exemplo: HTML5 tem fulano, CSS tem ciclano, etc. Eu acredito que se cada um pegar pra si uma área, fica mais fácil de controlar. Porém é apenas uma ideia.

**Comment by bernardodiasc** [comment]
Acho ambas as responsabilidades válidas. O projeto em si precisa de um coordenador, que é aquele que mantem as ideias afinadas, alinhadas e em movimento. Não só as ideias, como as pessoas também. Então no que relaciona ao conteúdo é preciso que algumas pessoas responsabilizem-se por um ou mais tópicos. Estas irão dar o ponta-pé inicial em cada tema/tópico e moderar o que for contribuido por outros que participarem. Chama-se responsabilidade, tem que pegar e fazer. (galera, não sou rude, sou prático, ok? como o Tárcio disse, isso não é briga, é discussão ;)

Ao meu ver essa Issue do sumário são só sugestões mesmo, pois o que importa mesmo é quem está disposto a escrever, e sobre o que. A verdade é que o livro terá o que nós escrevermos não o que planejarmos escrever.

Da minha parte, poderia escrever material menos técnico, que entraria mais no Volume 5 e também no Volume 1. Gostaria de escrever sobre Symphony (que é minha especialidade) e tambem contribuir com material sobre Git.

Mas vou deixar bem avisado que meu tempo está limitadíssimo durante alguns meses, no que depender de mim, as coisas vão ser lentas por enquanto, até normalizar aqui (estou abrindo uma empresa, treinando funcionários, abrindo mercado, atendendo clientes e desenvolvendo... uff).

**Comment by tarciozemel** [comment]
@bernardodiasc Concordo plenamente! Então vamos definir o que, exatamente, vai entrar no **Volume 1**, para abrirmos a "chamada" para os voluntários que querem escrever. Acho que não há problemas em mais de uma pessoa entrar num tema, se vários estiverem interessados; mas, como citado, teria que pegar um "organizador" para não virar bagunça.

Atualmente, há um milestone antigo no repo, de antes de termos essa ideia de volumes; pode apagar e criar um para o Vol 1, propriamente dito, pessoal?

**Comment by mayroncachina** [comment]
Uma dica seria usar o Google Calendar, para definir as datas de entrega do material, ou pelo menos uma estimativa...

Criaria-se a agenda e compartilharia com todos com a opçao de edição, assim os responsáveis por cada parte do livro poderias verificar os trabalhos...

**Comment by leandroruel** [comment]
@bernardodiasc boa, falar sobre o symphony, que é um CMS ainda novo, seria bom, será que falar sobre, como aplicar CSS na prática em uma página seria uma boa? EX: um capítulo sobre estilizar elementos? como se fosse um exercício?

**Comment by bernardodiasc** [comment]
aplicar css no symphony? não entendi direito.

o Symphony na verdade não é tão novo. a versão 2.0 que foi lançada em 2008. eu gostaria de falar sobre o CMS, pq gosto demais dele. é tipo a ferramenta dos sonhos para fazer sites (e olha que sou um legítimo garimpeiro de "resources") e a comunidade é nota 10. a evolução no meu aprendizado quando me aproximei da comunidade foi igual um foguete e agora está havendo preparativos para iniciar o desenvolvimento do Symphony 3, e com certeza vou contribuir!

o pessoal lá tambem já discutiu sobre mudar o nome (denovo) por causa da confusão com o framework Synfony... mas são assuntos delicados.. hehehehe e tb é outra história.

**Comment by leandroruel** [comment]
@bernardodiasc nao nao, no symphony nao mano...hehe, tava falando de outra coisa já, um capitulo de exercícios de CSS, após alguns volumes de CSS. o Symphony é uma boa ideia que é separado disso que eu disse

**Comment by bernardodiasc** [comment]
ah sim.. exercícios são bons pra fixação...

há 2 semanas meu cunhado veio trabalhar comigo, zero de experiência em html, css, js, git e tudo mais. o cara tem experiência com python e blender (modelagem 3D). hoje já temos o primeiro frontned todo pronto e já iniciamos o backend. digo, praticar num exemplo real com umas boas dicas da um avanço violento.

basicamente dei 1 semana pra ele ler sobre html, css, jquery e git. na outra semana começamos a executar um projeto real, usando git. expliquei a metodologia antes de por a mão na massa, os cortes, webfonts, html5, e começamos apenas o html, em uns 2 dias todas as páginas (só html) estavam prontas e todos os arquivos de imagens cortados. pelo git ele me enviava cada pagina html e eu ia comentando o código e ajudando a melhorar.
alguns dias depois o css estava todo pronto, nessa etapa dei uma ajuda maior, expliquei vários conceitos comuns, css3, image replacemente, clearfix, etc. no inicio dessa semana apontei alguns plugins jquery e ele conseguiu instalar tudo quase sozinho. ontem e hoje ele ficou por conta do backend (symphony)...

enfim, o que quero dizer é que usando um exemplo real da pra abordar uma penca de técnicas, e a prática ajuda na fixação do aprendizado teórico anteriormente lido.

**Comment by marcelomatz** [comment]
Que baita história essa que o @bernardodiasc contou aí. Um exemplo nítido que prova o quanto o conhecimento tem quer ser compartilhado.

**Comment by leandroruel** [comment]
poxa, teacher monstro hein?

**Comment by bernardodiasc** [comment]
o mérito do aluno! =]

(ou do chicote estalando na cacunda do escragiário! muahahaha)

a proposito, hoje ele ficou várias horas por conta de colocar conteúdo de teste no sistema... fica a dica, não aceitem trabalhar sem o conteúdo oficial... essas várias horas são horas perdidas, e várias outras horas terão que ser gasta pra colocar o conteúdo oficial e provavelmente haverão alterações no projeto e mais código (mais horas) pra adaptar...

**Comment by tarciozemel** [comment]
@bernardodiasc mussumipsum.com

**Comment by leandroruel** [comment]
@tarciozemel HUEhehuehu

**Comment by bernardodiasc** [comment]
:+1: boa!

curti esse tb que alguem mandou lá no G+ http://www.picksumipsum.co.uk/

**Comment by bernardodiasc** [comment]
o que acham do http://www.mediawiki.org/wiki/MediaWiki ?

**Comment by tarciozemel** [comment]
@bernardodiasc Tá falando para nosso projeto?

**Comment by bernardodiasc** [comment]
isso, é o sistema da Wikipedia!

**Comment by mayroncachina** [comment]
Ja temos algum dominio?
Com certeza um wiki para organizar as informações é muito melhor do que deixar perdido aqui pelo github...

**Comment by tarciozemel** [comment]
@bernardodiasc @mayroncachina O bom do GitHub é poder controlar as versões, poder trabalhar com milestones, ter o espaço para discussões e, claro, aqui é o "habitat natural" para quem gosta de contribuir em projetos voluntários (e, até para os que estão iniciando, é fácil de entender, mexer e participar).

Devido a todas as características do GitHub especificamente feitas para gerenciamento e organização de projetos colaborativos escritos (em qualquer "linguagem"), não entendi bem o termo "perdido pelo GitHub"...

**Comment by leandroruel** [comment]
depois que o projeto ficar pronto...e...tivermos um domínio no ar para hospedar o livro, aí essa wiki podia entrar lá. e pelo github a gente continua com a evolução dos volumes

**Comment by bernardodiasc** [comment]
o wiki tambem tem controle de versão, e é violento exatamente pra esse tipo de conteúdo "enciclopédico"...

mas se preferen o github, então ok, acho que já temos um veredito. e voltando lá atrás a uma pergunta não respondida do @tarciozemel:

> Atualmente, há um milestone antigo no repo, de antes de termos essa ideia de volumes; pode apagar e criar um para o Vol 1, propriamente dito, pessoal?

meu voto é Sim! de SIMBORA! =]

acho que podemos então partir pro ataque. quem se habilita a dar o pontapé inicial?

fica definido que o livro será escrito aqui mesmo no github. As Issues são boas para discutir tópicos específicos (mas não é o lugar certo pra escrever o livro), sendo assim o material do livro deverá estar neste repo num formato de código ou no wiki do github. no caso de ser código, por que não nosso bom e velho html... até sugeriria algo mais robusto, baseado em arquivos e com sistema de template, que pudesse ser visualizado diretamente pelo github, este seria o caso do Jekyll, por exemplo. Mas isso dificultaria um bocado as coisas antes de facilitar.

digo, se eu fosse escrever meu primeiro parágrafo de conteúdo para o livro, onde seria? como as pessoas teriam acesso a este? e como outras pessoas poderiam contribuir com correções e adições ao que eu produzi?

**Comment by marcelomatz** [comment]
Partiu tocar esse projeto para frente. @tarciozemel Meu voto também é sim. :)
