### ISSUE TITLE
proposta de capas para o livro.

### ISSUE THREAD

**Issue by leandroruel** [desenvolvedoresweb/livros#6]
aqui vai a primeira proposta de capa já apresentada anteriormente na comunidade, com o tempo vou postando mais capas diferentes e vamos discutindo aquela que se adequar melhor a este projeto.

![capa_e-book](https://f.cloud.github.com/assets/2836002/463086/efd242fe-b517-11e2-8214-0164199ac5e6.png)

**Comment by marcelomatz** [comment]
+1

**Comment by natanaelphp** [comment]
:+1:

**Comment by tarciozemel** [comment]
:+1:

**Comment by tarciozemel** [comment]
Para os que enviaram e/ou vão enviar propostas de capas, estamos discutindo se não será melhor dividirmos em volumes esse primeiro livro. Deem uma olhada na issue https://github.com/desenvolvedoresweb/livros/issues/5.

Se for o caso, talvez o trabalho de design para a capa tenha que ser repensado para algo mais "integrado", por assim dizer.

Vão lá e opinem para saber se, realmente, dividir em volumes é algo que a maioria concorda e acha que vai melhor.
