### ISSUE TITLE
Definição do sumário do Volume 1 da coleção "Desenvolvimento Web"

### ISSUE THREAD

**Issue by tarciozemel** [desenvolvedoresweb/livros#8]
Vamos, então, discutir o que vai entrar nesse **Volume 1**. Como já (mais ou menos) combinamos, seria algo bem introdutório, sem tantas coisas técnicas, mais para ser uma introdução ao mundo webdev e apresentar as possibilidades às pessoas que ainda desconhecem a área.

Tópicos sobre como surgiu a internet e a web, como se dá a comunicação na rede, protocolos, cliente-servidor, o que é o navegador e as principais opções e "camadas" do desenvolvimento, na minha opinião, deveriam constar (mas não se limitar) neste livro.

Após chegarmos a um certo consenso sobre quais serão os tópicos para essa primeira versão do **Volume 1** - por ser um projeto colaborativo _sobre desenvolvimento web_ você não pensou que seria algo imutável, né?  ;-) -, proponho que abramos outra issue para definir qual(is) pessoa(s) ficará(ão) reponsável(eis) por cada tópico e, para cada um, criamos outras respectivas issues para ficar mais bem organizado (momento em que poderemos definir uma data para o fechamento da milestone).

Vamos lá?  :sake:

**Comment by leandroruel** [comment]
eu invoco os poderes da fênix neste repositório.

**Comment by tarciozemel** [comment]
Tá, então vamos ver se nós, mesmos, chamamos as pessoas para os respectivos tópicos. Vamos ver pelo naipe do povo lá na comunidade qual poderia escrever tal ou qual capítulo do Vol 1.

**Comment by leandroruel** [comment]
demorou!
